# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Highercomve.Oriel
PackageVersion: 0.6.12
PackageLocale: en-US
Publisher: Sergio Marin
PublisherUrl: https://highercomve.github.io/Oriel/
PackageName: Oriel
PackageUrl: https://highercomve.github.io/Oriel/
License: MIT
LicenseUrl: https://github.com/highercomve/Oriel/blob/main/LICENSE
ShortDescription: 'The Oriel CLI: build desktop apps with Zig and a web frontend'
Moniker: oriel
Tags:
- zig
- desktop
- framework
- webview
- cli
ReleaseNotesUrl: https://github.com/highercomve/Oriel/releases/tag/v0.6.12
ManifestType: defaultLocale
ManifestVersion: 1.10.0
