# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Highercomve.Oriel
PackageVersion: 0.6.20
InstallerType: portable
Commands:
- oriel
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.20/oriel-x86_64-windows.exe
  InstallerSha256: 61A89F60E5F463728053A389D46DB07CB3F00889E564017E5B9726DF74955C22
- Architecture: arm64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.20/oriel-aarch64-windows.exe
  InstallerSha256: BC2446DA0B5BA185D488C0B1B1943204C5BD4DE8EF9374EF5A7E8592D169BE20
ManifestType: installer
ManifestVersion: 1.10.0
