# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Highercomve.GhostPen
PackageVersion: 0.2.10
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: dev.ghostpen.Oriel
AppsAndFeaturesEntries:
- DisplayName: GhostPen
  Publisher: Sergio Marin
  ProductCode: dev.ghostpen.Oriel
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/highercomve/GhostPen/releases/download/v0.2.10/ghostpen-0.2.10-setup.exe
  InstallerSha256: 7B90B3E08A288572CD0BE02D491848D286768ADF00A69E5D8F558DA36D01D053
ManifestType: installer
ManifestVersion: 1.10.0
