# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Highercomve.Oriel
PackageVersion: 0.6.14
InstallerType: portable
Commands:
- oriel
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.14/oriel-x86_64-windows.exe
  InstallerSha256: 8DE3FD96FE70AF551CB75176BF67DF42819C2FE21320D0EF85C20A47F69837D9
- Architecture: arm64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.14/oriel-aarch64-windows.exe
  InstallerSha256: B4264FD6E623CBA205285E5147315404EE116EA633ED5BC6881BE4511C10D46E
ManifestType: installer
ManifestVersion: 1.10.0
