# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Highercomve.GhostPen
PackageVersion: 0.2.13
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: dev.ghostpen.Oriel
AppsAndFeaturesEntries:
- DisplayName: GhostPen
  Publisher: Sergio Marin
  ProductCode: dev.ghostpen.Oriel
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/highercomve/GhostPen/releases/download/v0.2.13/ghostpen-0.2.13-setup.exe
  InstallerSha256: AD3A4B776015B3E4B328327625B3DF2BD32DFE7E9D86038236A04110582F2888
ManifestType: installer
ManifestVersion: 1.10.0
