# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Highercomve.Oriel
PackageVersion: 0.6.22
InstallerType: portable
Commands:
- oriel
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.22/oriel-x86_64-windows.exe
  InstallerSha256: C6FFDCE94E05155D874EA4BC386656C42AE136C5899E21B677A28759007D0F4E
- Architecture: arm64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.22/oriel-aarch64-windows.exe
  InstallerSha256: 8465D64D4903A15644DF146F8A51AA94F5EDA80633B37B66B1285CB300023452
ManifestType: installer
ManifestVersion: 1.10.0
