# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Highercomve.Oriel
PackageVersion: 0.6.19
InstallerType: portable
Commands:
- oriel
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.19/oriel-x86_64-windows.exe
  InstallerSha256: C8A9AC169EB30387EB0E7D8294E94D222AA6055D2E93CE80A6575886451528C0
- Architecture: arm64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.19/oriel-aarch64-windows.exe
  InstallerSha256: 7FE3BEA07676A6E4D50ACDD4FF4D7E20D2E027FD0E5956672F7AC63D35FD3444
ManifestType: installer
ManifestVersion: 1.10.0
