# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Highercomve.Oriel
PackageVersion: 0.6.18
InstallerType: portable
Commands:
- oriel
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.18/oriel-x86_64-windows.exe
  InstallerSha256: 019C22C390455E3F89F57E375EDF81901DB87AD7DEB6FA80561C8DD03A4E8035
- Architecture: arm64
  InstallerUrl: https://github.com/highercomve/Oriel/releases/download/v0.6.18/oriel-aarch64-windows.exe
  InstallerSha256: 1FAB9E45368FE58109A446C4B57B8EF6493382A53396E131690D186C93A203EE
ManifestType: installer
ManifestVersion: 1.10.0
